name: Clean Outdated URL
run-name: 🧹 Clean Outdated URL

on:
  schedule:
    - cron: "0 0 */14 * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: job-data-sync
  cancel-in-progress: false

jobs:
  clean-outdated-url:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # ✅ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.PAT }}

      # ✅ Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.7.0

      # ✅ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      # ✅ Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # ✅ Clean Outdated URL
      - name: Clean Outdated URL
        id: clean-outdated-url
        run: pnpm clean-url

      - name: Commit and push updated data
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@github.com"

          git add data/
          git commit -m "chore(clean-outdated-url): clean outdated url"

      - name: Rebase and push
        uses: ./.github/actions/rebase-push
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.ref_name }}
